### ISSUE TITLE
/command all | %target% not found

### ISSUE THREAD

**Issue by tenshiku** [firewolf8385/ChatFeelingsReloaded#9]
**Describe the bug**
When non-op players who have the permission **cfr.use.all** do /command all it shows up with %target% not found. Works fine for people who are opped.

**To Reproduce**
1. Load the plugin on your server
2. Do /command all
4. No errors pop up besides, http://prntscr.com/mznynx

**Expected behavior**
Expected it to allow players to do action/feeling commands towards everyone on the server.

**Comment by firewolf8385** [comment]
Whoops, I put the wrong permission on the description page. It should be "cfr.send.all". Hopefully that works. This also exposed a bug with placeholders.
